### PR TITLE
Return widget instance from show_panel.

### PR DESCRIPTION
**Pull request by colingimenez**

### CODE REVIEW

**Comment by josh-t** [comment]
Hey Colin! Thanks for this! We'll have a quick chat internally in our next meeting, but we'll likely merge this asap.

**Comment by josh-t** [comment]
Sorry for the delay. We will QA this and push it out as soon as we can. Thanks again for the PR Colin!!

**Comment by colingimenez** [comment]
Fantastic! Glad to contribute :D

**Comment by josh-t** [comment]
Hi Colin! Sorry for the delayed response. The change was QA approved and ready for release. We have one other set of changes to `tk-desktop` that are currently in QA and this will be packaged with those. Should be out very soon. Thanks again!

**Pull request merged**
